import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { writeFileSync } from 'fs';

// ============================================================================
// QasidAI — Wallet Generator
// Generates a fresh wallet for QasidAI's on-chain identity on Base L2
// Run: npx tsx src/net/generate-wallet.ts
// ============================================================================

const privateKey = generatePrivateKey();
const account = privateKeyToAccount(privateKey);

// Write private key to a file instead of printing to terminal (opsec safety)
const envContent = `# Generated by QasidAI wallet generator — ${new Date().toISOString()}
# ⚠️  DELETE THIS FILE after copying the key to your .env
NET_PRIVATE_KEY=${privateKey}
`;

try {
   writeFileSync('.env.generated', envContent, { mode: 0o600 }); // owner-only read/write
   console.log(`
╔═══════════════════════════════════════════════════════════╗
║   QasidAI — Fresh Wallet Generated                       ║
╚═══════════════════════════════════════════════════════════╝

  📍 Address:     ${account.address}
  ⛓️  Chain:       Base (Chain ID: 8453)
  🔑 Private key saved to: .env.generated

  Next steps:
  1. Copy NET_PRIVATE_KEY from .env.generated into your .env file
  2. DELETE .env.generated immediately after copying
  3. Set NET_ENABLED=true in your .env
  4. Fund the wallet address with ~$0.50 of ETH on Base
     → Send Base ETH to: ${account.address}
     → You can bridge ETH to Base at https://bridge.base.org

  🔐 SECURITY: The private key was NOT printed to your terminal.
     It is saved in .env.generated with restricted permissions.
     Delete that file after copying the key to .env.
     Never share this key or commit it to git.
`);
} catch (error) {
   // Fallback: if file write fails, print with a warning
   console.error('⚠️  Could not write .env.generated file. Printing to terminal as fallback:');
   console.log(`  🔑 Private Key: ${privateKey}`);
   console.log(`  📍 Address:     ${account.address}`);
   console.log('  ⚠️  CLEAR YOUR TERMINAL HISTORY after copying the key.');
}
